pip install python-nmap
pip install google
pip install ipaddress
pip install re
pip install time
pip install nmap
pip install requests
pip install os
pip install platform
pip install subprocess
pip install threading
pip install googlesearch
pip install pandas
pip install datetime
pip install dateutil
pip install reportlab
pip install netaddr
pip install prettytable